baseurl = "https://greguz.github.io/personal-blog/"
languageCode = "en-us"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "ggblog"
    subtitle = "Yet another blog from another coding guy"
    keywords = ["blog", "coding"]
    copyright = "Giacomo Gregoletto"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = ">_"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
